trikoder_oauth2:

    authorization_server:
        private_key: '/home/coeus/projects/review/var/oauth/private.key'
        private_key_passphrase: college

        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'

        access_token_ttl:     PT2H

    resource_server:
        public_key: '/home/coeus/projects/review/var/oauth/public.key'

    persistence:
        doctrine: null
